name: tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: rar
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: PHPUnit
        uses: chindit/actions-phpunit@master
      - name: PHPStan
        uses: chindit/actions-phpstan@master
        with:
          arguments: 'src/ --level=9'
